### ISSUE TITLE
Voting bot

### ISSUE THREAD

**Issue by dbousamra** [charleso/haskell-in-haste#39] opened 2015-11-14 23:47 UTC
From coffee

module Chat.Bot.Vote where

import           Chat.Bot.Answer.Vote
import           Chat.Bot.Misc.Vote
import           Chat.Data
## -- This requires implementing comparing two numbers and display a message depending on the result

-- >>> guessMe 1 2
-- GuessLower
-- >>> guessMe 2 1
-- GuessHigher
-- >>> guessMe 2 2
-- GuessCorrect

data PollQuestion = PollQuestion String Int
"Zebra, 4"
"Tiger 7"
data Poll = Poll String [PollQuestion]
"What is you favorite animal" 

createVote :: String -> [String] -> Poll
createVote question names = Poll question (map (\n -> PollQuestion n 0) names)

addVote :: Poll -> String -> Pool
addVote (Poll question votes) votingFor =
  let updateQuestion (PollQuestion q v) =
       PollQuestion q (if q == votingFor then v + 1 else v)
  in  Poll question (map updateQuestion votes)

render :: Poll -> String

**Comment by charleso** [comment] 2015-11-15 02:05
Dupe of https://github.com/charleso/haskell-in-haste/issues/38

**Closed as completed by charleso** 2015-11-15 02:05 UTC
